name: CI
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: rust:trixie
    steps:
      - uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get install build-essential
      # - name: Install Rust
      #   uses: dtolnay/rust-toolchain@stable
      - name: make check
        run: make check
