name: Dependencies Update

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-update
        run: cargo install cargo-update

      - name: Update dependencies
        run: |
          cargo update
          git status --porcelain

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): update Rust dependencies"
          title: "Update Rust dependencies"
          body: |
            Mise à jour automatique des dépendances Rust via cargo-update.
          branch: bot/update-dependencies
          labels: bot/update
