name: quality-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  quality:
    runs-on: ubuntu-latest
    container:
      image: python:3.13.11-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#Install rust +fmt
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Cargo check
        run: make check

      - name: Cache python venv
        id: cache-python
        uses: actions/cache@v4
        with:
          path: .venv
          key: python-${{ runner.os }}-${{ hashFiles('**/*.py') }}

      - name: Setup Python venv
        run: python -m venv .venv
      
      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}        
        name: Activate venv and install black
        run: |
          . .venv/bin/activate
          pip install black

      - name: Check Python formatting
        run: .venv/bin/black --check .
        continue-on-error: true