name: quality-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    container:
      image: python:3.13.11-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache rust packages
        id: cache-rust-quality
        uses: actions/cache@v4
        with:
          path: |
               /usr/local/cargo/registry
               /usr/local/cargo/bin
          key: rust-${{ runner.os }}-${{ hashFiles('**/cargo.lock') }}

#Install rust +fmt
      - if: ${{ steps.cache-rust-quality.outputs.cache-hit != 'true' }}        
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Cargo check
        run: make check

      - name: Cache python venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: python-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      - name: Setup Python venv
        run: python -m venv .venv

      - name: Activate venv and install black
        run: |
          . .venv/bin/activate
          pip install black

      - name: Check Python formatting
        run: .venv/bin/black --check .