name: quality-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    container:
      image: python:3.13.11-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#Install rust +fmt
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Cargo check
        run: make check

      # - name: Cache python packages
      #   id: cache-python
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #         /?
      #     key: python-${{ runner.os }}-${{ hashFiles('**/?.lock') }}

      # - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}        
      #   name: Install Python tools
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip install black

      - name: Check Python formatting
        run: make python-check