name: quality-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    container:
      image: python:3.13.11-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache rust packages
        id: cache-rust-quality
        uses: actions/cache@v4
        with:
          path: |
              ~/.cargo
              target
          key: rust-quality-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - if: ${{ steps.cache-rust-quality.outputs.cache-hit == 'true' }}        
        name: Ajout path cargo
        run: echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"

#Install rust +fm
      - if: ${{ steps.cache-rust-quality.outputs.cache-hit != 'true' }}        
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      # - if: ${{ steps.cache-rust-quality.outputs.cache-hit != 'true' }}        
      #   name: Set Rust default toolchain
      #   run: rustup default stable

      - name: Cargo check
        run: make check

      - name: Cache python venv
        id: cache-python
        uses: actions/cache@v4
        with:
          path: .venv
          key: python-${{ runner.os }}-${{ hashFiles('**/*.py') }}

      - name: Setup Python venv
        run: python -m venv .venv
      
      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}        
        name: Activate venv and install black
        run: |
          . .venv/bin/activate
          pip install black

      - name: Check Python formatting
        run: .venv/bin/black --check .
        continue-on-error: true