name: WILLIAM_Update
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    name: update dependancies
    runs-on: ubuntu-latest
    container:
      image: rust:trixie
    steps:
      - uses: actions/checkout@v4

      - name: update cargo dependancies
        run: cargo update
